# Server IP Address
SERVER_IP_ADDR: 141.223.199.27
SERVER_PORT: 8080

# Maximum buffer size
MAX_BUF_SIZE: 1024

# ---- Robot Arm Configuration ----
# Robot Number (Starts from 0)
ROBOT_ARM_NUM: 0

# GPIO Pins
## GPIO[0] : Up-LEFT / GPIO[1] : Up-RIGHT
## GPIO[2] : Down-LEFT / GPIO[3] : Down-RIGHT
GPIO_WHEEL_DIRPINS: [19, 6, 20, 12] # GPIO DIR PINS
GPIO_WHEEL_STPPINS: [26, 13, 21, 16] # GPIO STEPPER PINS

GPIO_ARM_DIRPINS: [8, 10, 23] # GPIO DIR PINS
GPIO_ARM_STPPINS: [7, 9, 24] # GPIO STEPPER PINS

GPIO_SERVO_PIN: 0 # GPIO DIR PINS

# C_Motor Configurations
MOTOR_WHEEL_ANG_PER_SEC: 1.8
MOTOR_WHEEL_GEAR: 1.0
# C_Motor Configurations
MOTOR_ARM_ANG_PER_SEC: 1.8
MOTOR_ARM_GEAR: 10.0

# Default Max Velocity for each operation
VEL_DEFAULT_MAX_FORWARD: 0.9
VEL_DEFAULT_MAX_RIGHT: 0.9
VEL_DEFAULT_MAX_ROTATION: 0.9

# Fixed Initial Position (mm)
## Only for CITD III, Fixed Initial Position for Trajectory Seperation
INIT_POS: [500, 500]

# Distance between Center of Robot & Axis of Robot Arm
ROBOTARM_L1 : 145
ROBOTARM_L2 : 180

# Robot Arm config for initialize and motion control
ROBOTARM_MAX_ANGLES : [200.0, 200.0, 360.0]
ROBOTARM_MIN_ANGLES : [-1.0, -1.0, -1.0]

# Robot Arm Positions for stacking and lifting
ROBOTARM_INITIAL_POSITION : [200.0, -71.0]
ROBOT_ARM_BEFORE_WORK: 200.0
ROBOT_ARM_MOVING_POSITION : [70.0,100.0]

# ---- Robot Arm Configuration ----


# ---- Server Configuration ----
# Maximum # of robots connected
MAX_ROBOT_CONNECTED: 2

# Resolution for Image Capture
RESOLUTION_WIDTH: 640
RESOLUTION_HEIGHT: 480

# Frame to process (time)
PROCESS_FRAME_INTERVAL: 10

# Color Sensitivity (HSV - Hue)
COLOR_SENSITIVITY: 8

# RED : (4-101)
# Blue :

# Robot Arm Hue Value
# Red : 4, Blue : 88
ROBOT_ARM_HUE: 4

# Color Threshold (HSV - Hue Blue:88, Red:101)
COLOR_THRESHOLD: 101
# Morphology Kernel Size (Default : 4)
COLOR_MORPH_KERNEL_SIZE: 4

HEURISTICS_DIST: 10
HEURISTICS_DIR: 18

# Experimental Decision
# 1 Pixel : X mm (2705 : 2040 := 640 : 480 ==> X := 4.23)
MM_PER_PIXEL: 4.23

# TODO: CHECK
# 1 MM : Y Degree (Wheel)
DEGREE_PER_MM_FORWARD: 0.3
DEGREE_PER_MM_RIGHT : 0.5
# 1 Degree (Body) : Z Degree (Wheel)
DEGREE_PER_ANGLE_ROTATION : 0.7

# Distance between Center Position and Head Sticker (mm) (Fin)
CENTER_DIST_FROM_STICKER_MM: 33

# Estimated Robot Size Diameter (mm) (Blocks Unabled)
ROBOT_BODY_SIZE_MM: 530

# Diameter of Minimun area for
ROBOT_ROTATING_DIAMETER: 600

# Position of center of motor in arm
ROBOT_MOTOR_POS: [0.0,0.0]
ROBOT_MOVING_POSTURE: [0.0,0.0]

# ---- Server Configuration ----

# ---- GUI Configuration ----
ROBOT_IMG_POS_0: [30, 200]
ROBOT_IMG_POS_1: [930, 200]

RESOLUTION_WIDTH_GUI: 640
# ---- GUI Configuration ----
