# Server IP Address
SERVER_IP_ADDR: 141.223.199.27
SERVER_PORT: 8080

# Maximum buffer size
MAX_BUF_SIZE: 1024

# ---- Robot Arm Configuration ----
# Robot Number (Starts from 0)
ROBOT_ARM_NUM: 0

# Color of Sticker for CV Detection (RGB)
ROBOT_ARM_COLOR: [240, 0, 0]

# GPIO Pins
## GPIO[0] : Up-LEFT / GPIO[1] : Up-RIGHT
## GPIO[2] : Down-LEFT / GPIO[3] : Down-RIGHT
GPIO_WHEEL_DIRPINS: [19, 27, 5, 23] # GPIO DIR PINS
GPIO_WHEEL_STPPINS: [26, 22, 6, 24] # GPIO STEPPER PINS

GPIO_ARM_DIRPINS: [0, 0, 0] # GPIO DIR PINS
GPIO_ARM_STPPINS: [0, 0, 0] # GPIO STEPPER PINS

GPIO_SERVO_PIN: 0 # GPIO DIR PINS

# C_Motor Configurations
MOTOR_WHEEL_ANG_PER_SEC: 1.8
MOTOR_WHEEL_GEAR: 1.0
# C_Motor Configurations
MOTOR_ARM_ANG_PER_SEC: 0.425
MOTOR_ARM_GEAR: 0.45

# Default Max Velocity for each operation
VEL_DEFAULT_MAX_FORWARD: 1.5
VEL_DEFAULT_MAX_RIGHT: 1.5
VEL_DEFAULT_MAX_ROTATION: 1.5

# Fixed Initial Position (mm)
## Only for CITD III, Fixed Initial Position for Trajectory Seperation
INIT_POS: [15.0, 0.0]

# Robot Arm Configuration (mm)
ROBOTARM_L1: 145
ROBOTARM_L2: 180

# ---- Robot Arm Configuration ----


# ---- Server Configuration ----
# Maximum # of robots connected
MAX_ROBOT_CONNECTED: 2

# Resolution for Image Capture
RESOLUTION_WIDTH: 640
RESOLUTION_HEIGHT: 480

# Frame to process (time)
PROCESS_FRAME_INTERVAL: 10

# TODO: Experimental Decision
# 1 Pixel : X mm
MM_PER_PIXEL: 0.3
# 1 MM : Y Degree (Wheel)
DEGREE_PER_MM_FORWARD: 0.3
DEGREE_PER_MM_RIGHT : 0.5
# 1 Degree (Body) : Z Degree (Wheel)
DEGREE_PER_ANGLE_ROTATION : 0.7

# Distance between Center Position and Head Sticker (mm)
CENTER_DIST_FROM_STICKER_MM: 7

# Estimated Robot Size (mm) (Blocks Unabled)
ROBOT_BODY_SIZE_MM: 150

# Diameter of Minimun area for
ROBOT_ROTATING_DIAMETER: 250

#Position of center of motor in arm
ROBOT_MOTOR_POS: [0.0,0.0]
ROBOT_MOVING_POSTURE: [0.0,0.0]

# Color Sensitivity (HSV - Hue)
COLOR_SENSITIVITY: 25
# ---- Server Configuration ----

# ---- GUI Configuration ----
ROBOT_IMG_POS_0: [30, 200]
ROBOT_IMG_POS_1: [930, 200]

RESOLUTION_WIDTH_GUI: 640
# ---- GUI Configuration ----
