# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FinalDemo.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from S_GUI.ClickableQLabel import PicButton

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 930)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.robo0_img = QtWidgets.QLabel(self.centralwidget)
        self.robo0_img.setGeometry(QtCore.QRect(30, 200, 640, 480))
        self.robo0_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.robo0_img.setObjectName("robo0_img")
        self.robo1_img = QtWidgets.QLabel(self.centralwidget)
        self.robo1_img.setGeometry(QtCore.QRect(930, 200, 640, 480))
        self.robo1_img.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.robo1_img.setObjectName("robo1_img")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(22)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 1600, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 55, 1600, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 95, 1600, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1329, 150, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.button_start.setObjectName("button_start")

        # Changed
        self.button_stop = PicButton("./S_GUI/Images/stop_n.png", "./S_GUI/Images/stop_r.png", "./S_GUI/Images/stop_c.png", (self.centralwidget))
        self.button_stop.setGeometry(QtCore.QRect(710, 460, 180, 180))
        self.button_stop.setObjectName("button_stop")
        self.robo0_dat_pos = QtWidgets.QLabel(self.centralwidget)
        self.robo0_dat_pos.setGeometry(QtCore.QRect(200, 740, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(12)
        font.setItalic(True)
        self.robo0_dat_pos.setFont(font)
        self.robo0_dat_pos.setObjectName("robo0_dat_pos")
        self.robo0_dat_inst_on = QtWidgets.QLabel(self.centralwidget)
        self.robo0_dat_inst_on.setGeometry(QtCore.QRect(240, 780, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(12)
        font.setItalic(True)
        self.robo0_dat_inst_on.setFont(font)
        self.robo0_dat_inst_on.setObjectName("robo0_dat_inst_on")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(30, 700, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.robo0_dat_state = QtWidgets.QLabel(self.centralwidget)
        self.robo0_dat_state.setGeometry(QtCore.QRect(180, 700, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(12)
        font.setItalic(True)
        self.robo0_dat_state.setFont(font)
        self.robo0_dat_state.setObjectName("robo0_dat_state")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(30, 740, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(30, 780, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(30, 820, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.robo0_dat_inst_next = QtWidgets.QLabel(self.centralwidget)
        self.robo0_dat_inst_next.setGeometry(QtCore.QRect(200, 820, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(12)
        font.setItalic(True)
        self.robo0_dat_inst_next.setFont(font)
        self.robo0_dat_inst_next.setObjectName("robo0_dat_inst_next")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(1430, 700, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(1380, 780, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(1410, 740, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(1380, 820, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.robo1_dat_state = QtWidgets.QLabel(self.centralwidget)
        self.robo1_dat_state.setGeometry(QtCore.QRect(1000, 700, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(12)
        font.setItalic(True)
        self.robo1_dat_state.setFont(font)
        self.robo1_dat_state.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.robo1_dat_state.setObjectName("robo1_dat_state")
        self.robo1_dat_pos = QtWidgets.QLabel(self.centralwidget)
        self.robo1_dat_pos.setGeometry(QtCore.QRect(980, 740, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(12)
        font.setItalic(True)
        self.robo1_dat_pos.setFont(font)
        self.robo1_dat_pos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.robo1_dat_pos.setObjectName("robo1_dat_pos")
        self.robo1_dat_inst_on = QtWidgets.QLabel(self.centralwidget)
        self.robo1_dat_inst_on.setGeometry(QtCore.QRect(950, 780, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(12)
        font.setItalic(True)
        self.robo1_dat_inst_on.setFont(font)
        self.robo1_dat_inst_on.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.robo1_dat_inst_on.setObjectName("robo1_dat_inst_on")
        self.robo1_dat_inst_next = QtWidgets.QLabel(self.centralwidget)
        self.robo1_dat_inst_next.setGeometry(QtCore.QRect(980, 820, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(12)
        font.setItalic(True)
        self.robo1_dat_inst_next.setFont(font)
        self.robo1_dat_inst_next.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.robo1_dat_inst_next.setObjectName("robo1_dat_inst_next")
        self.progress_tot = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_tot.setGeometry(QtCore.QRect(600, 802, 400, 41))
        self.progress_tot.setProperty("value", 24)
        self.progress_tot.setObjectName("progress_tot")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(600, 770, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Laksaman")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.bg_img = QtWidgets.QLabel(self.centralwidget)
        self.bg_img.setGeometry(QtCore.QRect(0, 0, 1600, 930))
        self.bg_img.setObjectName("bg_img")
        self.bg_img.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.robo0_dat_pos.raise_()
        self.robo0_dat_inst_on.raise_()
        self.label_14.raise_()
        self.robo0_dat_state.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.robo0_dat_inst_next.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.robo1_dat_state.raise_()
        self.robo1_dat_pos.raise_()
        self.robo1_dat_inst_on.raise_()
        self.robo1_dat_inst_next.raise_()
        self.progress_tot.raise_()
        self.label_29.raise_()
        self.robo0_img.raise_()
        self.robo1_img.raise_()
        self.button_start.raise_()
        self.button_stop.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.robo0_img.setText(_translate("MainWindow", "Robot Image 1"))
        self.robo1_img.setText(_translate("MainWindow", "Robot Image 2"))
        self.label_3.setText(_translate("MainWindow", "Robot 1"))
        self.label_4.setText(_translate("MainWindow", "2019 Fall Session\n"
"CITE301 Creative iT Design - Advanced Design"))
        self.label_5.setText(_translate("MainWindow", "건축용 로봇 팔 제어 시스템 개발"))
        self.label_6.setText(_translate("MainWindow", "Development of Builder Robot Arms Management System"))
        self.label_7.setText(_translate("MainWindow", "Robot 2"))
        self.button_start.setText(_translate("MainWindow", "Start Button"))
        self.button_stop.setText(_translate("MainWindow", "Stop Button"))
        self.robo0_dat_pos.setText(_translate("MainWindow", "Position Data"))
        self.robo0_dat_inst_on.setText(_translate("MainWindow", "On-going Instruction Data"))
        self.label_14.setText(_translate("MainWindow", "Current State  : "))
        self.robo0_dat_state.setText(_translate("MainWindow", "State Data"))
        self.label_16.setText(_translate("MainWindow", "Current Position  : "))
        self.label_17.setText(_translate("MainWindow", "On-going Instruction  :"))
        self.label_18.setText(_translate("MainWindow", "Next Instruction  :"))
        self.robo0_dat_inst_next.setText(_translate("MainWindow", "Next Instruction Data"))
        self.label_20.setText(_translate("MainWindow", ": Current State"))
        self.label_21.setText(_translate("MainWindow", ": On-going Instruction"))
        self.label_22.setText(_translate("MainWindow", ": Current Position"))
        self.label_23.setText(_translate("MainWindow", ": Next Instruction"))
        self.robo1_dat_state.setText(_translate("MainWindow", "State Data"))
        self.robo1_dat_pos.setText(_translate("MainWindow", "Position Data"))
        self.robo1_dat_inst_on.setText(_translate("MainWindow", "On-going Instruction Data"))
        self.robo1_dat_inst_next.setText(_translate("MainWindow", "Next Instruction Data"))
        self.label_29.setText(_translate("MainWindow", "Total Progress"))
        self.bg_img.setText(_translate("MainWindow", "Background_Image"))
